// src/lib/header.svelte
<script>
    import {page_links} from "../links";
    import {beforeUpdate, onMount} from "svelte";

    let links = []
    let submenu

    beforeUpdate(()=>{
        page_links.forEach(itm => {
            if(itm.href !== window.location.pathname){
                links.push(itm)
            }
        })
    })
    onMount(()=>{

    })
</script>

<header>
    <a href="/">Home</a>
    <nav>
        <p>Topics</p>
        <div class="subtopics" bind:this={submenu}>
            {#each links as link}
                <ul>
                    <li>
                        <a href="{link.href}">{link.title}</a>
                    </li>
                </ul>
            {/each}
        </div>
    </nav>
</header>

<style lang="scss">
    header {
      display: flex;
    }

    .subtopics {
      position: absolute;
      z-index: 2;
      background:rgba(0,0,0,0.8);
      opacity:0;
      overflow: hidden;
      height:0;
      transition: all 0.5s ease;
    }

    nav{
      margin-left:20px;
    }

    nav:hover {
      cursor: pointer;
      .subtopics {
        opacity: 1;
        padding:20px;
        height:auto;
        transition: all 0.5s ease;
      }
    }

</style>

// islands/header.tsx
import {useEffect, useState} from "https://esm.sh/stable/preact@10.11.0/deno/hooks.js";

interface Link {
    href: string,
    title: string
}

export default function () {

    const [links, set_links] = useState([])
    const base_links = [
        {

            href: "/webgl",
            title: "WebGL"
        },
        {

            href: "/webgpu",
            title: "WebGPU"
        },
        {

            href: "/vulkan",
            title: "Vulkan"
        },
        {

            href: "/houdini",
            title: "Houdini"
        },
        {

            href: "/unreal",
            title: "Unreal Engine"
        },
        {
            href: "/misc",
            title: "Misc"
        }
    ]


    useEffect(() => {
        const tmp: Array<Link> = []
        base_links.forEach(itm => {
            if (itm.href !== window.location.pathname) {
                tmp.push(itm)
            }
        })

        set_links(tmp)
    }, [])

    return (
        <header>
            <a href="/">Home</a>
            <nav>
                <p>Topics</p>
                <div className="subtopics">

                </div>
            </nav>
        </header>
    )
}
